-- Generated by nwg-displays on 2026-09-12 at 09:04:55. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "DP-2",
    mode = "3840x2160@120.0",
    position = "1920x0",
    scale = 1,
    vrr = 0,
    transform = 1
})
hl.monitor({
    output = "DP-3",
    mode = "3840x2160@240.02",
    position = "4080x1680",
    scale = 1,
    vrr = 0
})
