# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/tsi/bin:$HOME/.composer/vendor/bin:$HOME/.local/bin:$HOME/bin:$HOME/go/bin:$PATH

alias ls='eza --icons'
alias l='eza -al -g --header --git --icons'
alias lg=lazygit

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Disable experimental warnings with node 23.x: https://github.com/npm/cli/issues/7857#issuecomment-2481331001
export NODE_OPTIONS='--disable-warning=ExperimentalWarning'

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export EDITOR="nvim"

eval "$(starship init zsh)"

# pnpm
export PNPM_HOME="/Users/nerdo/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin:$HOME/.cargo"

# For php 7.0
export LDFLAGS="-L/opt/homebrew/opt/php@7.0/lib"
export CPPFLAGS="-I/opt/homebrew/opt/php@7.0/include"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export GITHUB_TOKEN=$(cat ~/.github_token)
export GITHUB_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN
export GITHUB_MCP_TOKEN=$(cat ~/.github_mcp_token)
export JIRA_API_TOKEN=$(cat ~/.jira_api_token)
export TSI_OPENAI_API_KEY=$(cat ~/.tsi_openai_api_key)

# bun completions
[ -s "/Users/nerdo/.bun/_bun" ] && source "/Users/nerdo/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# prime barnacle
source ~/go/src/barnacle/barnacle.plugin.zsh

# keybinding for ctrl+r for history seems to be missing without this
bindkey "^R" history-incremental-search-backward 

# init zoxide
eval "$(zoxide init zsh)"
